// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.28.3
// source: mpi.proto

package mpi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source int32  `protobuf:"varint,1,opt,name=source,proto3" json:"source,omitempty"`
	Dest   int32  `protobuf:"varint,2,opt,name=dest,proto3" json:"dest,omitempty"`
	Tag    int32  `protobuf:"varint,3,opt,name=tag,proto3" json:"tag,omitempty"`
	Data   []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_mpi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_mpi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_mpi_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetSource() int32 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *Message) GetDest() int32 {
	if x != nil {
		return x.Dest
	}
	return 0
}

func (x *Message) GetTag() int32 {
	if x != nil {
		return x.Tag
	}
	return 0
}

func (x *Message) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RecvRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source int32 `protobuf:"varint,1,opt,name=source,proto3" json:"source,omitempty"` // -1 for any source
	Tag    int32 `protobuf:"varint,2,opt,name=tag,proto3" json:"tag,omitempty"`       // -1 for any tag
}

func (x *RecvRequest) Reset() {
	*x = RecvRequest{}
	mi := &file_mpi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecvRequest) ProtoMessage() {}

func (x *RecvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mpi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecvRequest.ProtoReflect.Descriptor instead.
func (*RecvRequest) Descriptor() ([]byte, []int) {
	return file_mpi_proto_rawDescGZIP(), []int{1}
}

func (x *RecvRequest) GetSource() int32 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *RecvRequest) GetTag() int32 {
	if x != nil {
		return x.Tag
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_mpi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_mpi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_mpi_proto_rawDescGZIP(), []int{2}
}

var File_mpi_proto protoreflect.FileDescriptor

var file_mpi_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6d, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6d, 0x70, 0x69,
	0x22, 0x5b, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x64, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x37, 0x0a,
	0x0b, 0x52, 0x65, 0x63, 0x76, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x74, 0x61, 0x67, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x32,
	0x55, 0x0a, 0x09, 0x4d, 0x50, 0x49, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x04,
	0x53, 0x65, 0x6e, 0x64, 0x12, 0x0c, 0x2e, 0x6d, 0x70, 0x69, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x1a, 0x0a, 0x2e, 0x6d, 0x70, 0x69, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x26,
	0x0a, 0x04, 0x52, 0x65, 0x63, 0x76, 0x12, 0x10, 0x2e, 0x6d, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x63,
	0x76, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x6d, 0x70, 0x69, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2e, 0x2f, 0x6d, 0x70, 0x69,
	0x3b, 0x6d, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mpi_proto_rawDescOnce sync.Once
	file_mpi_proto_rawDescData = file_mpi_proto_rawDesc
)

func file_mpi_proto_rawDescGZIP() []byte {
	file_mpi_proto_rawDescOnce.Do(func() {
		file_mpi_proto_rawDescData = protoimpl.X.CompressGZIP(file_mpi_proto_rawDescData)
	})
	return file_mpi_proto_rawDescData
}

var file_mpi_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_mpi_proto_goTypes = []any{
	(*Message)(nil),     // 0: mpi.Message
	(*RecvRequest)(nil), // 1: mpi.RecvRequest
	(*Empty)(nil),       // 2: mpi.Empty
}
var file_mpi_proto_depIdxs = []int32{
	0, // 0: mpi.MPIServer.Send:input_type -> mpi.Message
	1, // 1: mpi.MPIServer.Recv:input_type -> mpi.RecvRequest
	2, // 2: mpi.MPIServer.Send:output_type -> mpi.Empty
	0, // 3: mpi.MPIServer.Recv:output_type -> mpi.Message
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mpi_proto_init() }
func file_mpi_proto_init() {
	if File_mpi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mpi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mpi_proto_goTypes,
		DependencyIndexes: file_mpi_proto_depIdxs,
		MessageInfos:      file_mpi_proto_msgTypes,
	}.Build()
	File_mpi_proto = out.File
	file_mpi_proto_rawDesc = nil
	file_mpi_proto_goTypes = nil
	file_mpi_proto_depIdxs = nil
}
