// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: mpi.proto

package mpi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MPIServer_Send_FullMethodName = "/mpi.MPIServer/Send"
	MPIServer_Recv_FullMethodName = "/mpi.MPIServer/Recv"
)

// MPIServerClient is the client API for MPIServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MPIServerClient interface {
	Send(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Empty, error)
	Recv(ctx context.Context, in *RecvRequest, opts ...grpc.CallOption) (*Message, error)
}

type mPIServerClient struct {
	cc grpc.ClientConnInterface
}

func NewMPIServerClient(cc grpc.ClientConnInterface) MPIServerClient {
	return &mPIServerClient{cc}
}

func (c *mPIServerClient) Send(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, MPIServer_Send_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mPIServerClient) Recv(ctx context.Context, in *RecvRequest, opts ...grpc.CallOption) (*Message, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Message)
	err := c.cc.Invoke(ctx, MPIServer_Recv_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MPIServerServer is the server API for MPIServer service.
// All implementations must embed UnimplementedMPIServerServer
// for forward compatibility.
type MPIServerServer interface {
	Send(context.Context, *Message) (*Empty, error)
	Recv(context.Context, *RecvRequest) (*Message, error)
	mustEmbedUnimplementedMPIServerServer()
}

// UnimplementedMPIServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMPIServerServer struct{}

func (UnimplementedMPIServerServer) Send(context.Context, *Message) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedMPIServerServer) Recv(context.Context, *RecvRequest) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Recv not implemented")
}
func (UnimplementedMPIServerServer) mustEmbedUnimplementedMPIServerServer() {}
func (UnimplementedMPIServerServer) testEmbeddedByValue()                   {}

// UnsafeMPIServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MPIServerServer will
// result in compilation errors.
type UnsafeMPIServerServer interface {
	mustEmbedUnimplementedMPIServerServer()
}

func RegisterMPIServerServer(s grpc.ServiceRegistrar, srv MPIServerServer) {
	// If the following call pancis, it indicates UnimplementedMPIServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MPIServer_ServiceDesc, srv)
}

func _MPIServer_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPIServerServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MPIServer_Send_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPIServerServer).Send(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _MPIServer_Recv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecvRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPIServerServer).Recv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MPIServer_Recv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPIServerServer).Recv(ctx, req.(*RecvRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MPIServer_ServiceDesc is the grpc.ServiceDesc for MPIServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MPIServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mpi.MPIServer",
	HandlerType: (*MPIServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _MPIServer_Send_Handler,
		},
		{
			MethodName: "Recv",
			Handler:    _MPIServer_Recv_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mpi.proto",
}
